// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler v1.6.5 ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// be/be_codegen.cpp:381


#include "tcsServerC.h"
#include "tao/AnyTypeCode/Null_RefCount_Policy.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/AnyTypeCode/Alias_TypeCode_Static.h"
#include "tao/AnyTypeCode/Objref_TypeCode_Static.h"
#include "tao/AnyTypeCode/String_TypeCode_Static.h"
#include "tao/CDR.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "tao/CDR.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/AnyTypeCode/Any_Impl_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Object_Argument_T.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "tcsServerC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:73

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
  
  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:141

#if !defined (_ACS_RWDOUBLE__ARG_TRAITS_)
#define _ACS_RWDOUBLE__ARG_TRAITS_
  
  template<>
  class  Arg_Traits<ACS::RWdouble>
    : public
        Object_Arg_Traits_T<
            ACS::RWdouble_ptr,
            ACS::RWdouble_var,
            ACS::RWdouble_out,
            TAO::Objref_Traits<ACS::RWdouble>,
            TAO::Any_Insert_Policy_Stream <ACS::RWdouble_ptr>
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:60

// Traits specializations for acstcsServer::tcsServer.

acstcsServer::tcsServer_ptr
TAO::Objref_Traits<acstcsServer::tcsServer>::duplicate (
    acstcsServer::tcsServer_ptr p)
{
  return acstcsServer::tcsServer::_duplicate (p);
}

void
TAO::Objref_Traits<acstcsServer::tcsServer>::release (
    acstcsServer::tcsServer_ptr p)
{
  ::CORBA::release (p);
}

acstcsServer::tcsServer_ptr
TAO::Objref_Traits<acstcsServer::tcsServer>::nil (void)
{
  return acstcsServer::tcsServer::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<acstcsServer::tcsServer>::marshal (
    const acstcsServer::tcsServer_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// Function pointer for collocation factory initialization.
TAO::Collocation_Proxy_Broker * 
(*acstcsServer__TAO_tcsServer_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj
  ) = 0;

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void acstcsServer::tcsServer::displayMessage (
    void)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_tcsServer_Proxy_Broker_ == 0)
    {
      acstcsServer_tcsServer_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "displayMessage",
      14,
      this->the_TAO_tcsServer_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void acstcsServer::tcsServer::badMethod (
    void)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_tcsServer_Proxy_Broker_ == 0)
    {
      acstcsServer_tcsServer_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  static TAO::Exception_Data
  _tao_acstcsServer_tcsServer_badMethod_exceptiondata [] = 
    {
      {
        "IDL:alma/ACSErrTypeCommon/UnknownEx:1.0",
        ACSErrTypeCommon::UnknownEx::_alloc
#if TAO_HAS_INTERCEPTORS == 1
        , ACSErrTypeCommon::_tc_UnknownEx
#endif /* TAO_HAS_INTERCEPTORS */
      }
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "badMethod",
      9,
      this->the_TAO_tcsServer_Proxy_Broker_
    );
  
  _tao_call.invoke (
      _tao_acstcsServer_tcsServer_badMethod_exceptiondata,
      1
    );
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

::ACS::RWdouble_ptr acstcsServer::tcsServer::currentPositionAlpha (
    void)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_tcsServer_Proxy_Broker_ == 0)
    {
      acstcsServer_tcsServer_setup_collocation ();
    }
  
  TAO::Arg_Traits< ::ACS::RWdouble>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_currentPositionAlpha",
      25,
      this->the_TAO_tcsServer_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

::ACS::RWdouble_ptr acstcsServer::tcsServer::currentPositionDelta (
    void)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_tcsServer_Proxy_Broker_ == 0)
    {
      acstcsServer_tcsServer_setup_collocation ();
    }
  
  TAO::Arg_Traits< ::ACS::RWdouble>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_currentPositionDelta",
      25,
      this->the_TAO_tcsServer_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
  
  return _tao_retval.retn ();
}

acstcsServer::tcsServer::tcsServer (void)
 : the_TAO_tcsServer_Proxy_Broker_ (0)
{
  this->acstcsServer_tcsServer_setup_collocation ();
}

void
acstcsServer::tcsServer::acstcsServer_tcsServer_setup_collocation ()
{
  if (::acstcsServer__TAO_tcsServer_Proxy_Broker_Factory_function_pointer)
    {
      this->the_TAO_tcsServer_Proxy_Broker_ =
        ::acstcsServer__TAO_tcsServer_Proxy_Broker_Factory_function_pointer (this);
    }
  
  this->ACS_CharacteristicComponent_setup_collocation ();
}

acstcsServer::tcsServer::~tcsServer (void)
{}

void 
acstcsServer::tcsServer::_tao_any_destructor (void *_tao_void_pointer)
{
  tcsServer *_tao_tmp_pointer =
    static_cast<tcsServer *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

acstcsServer::tcsServer_ptr
acstcsServer::tcsServer::_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return
    TAO::Narrow_Utils<tcsServer>::narrow (
        _tao_objref,
        "IDL:alma/acstcsServer/tcsServer:1.0",
        acstcsServer__TAO_tcsServer_Proxy_Broker_Factory_function_pointer
      );
}

acstcsServer::tcsServer_ptr
acstcsServer::tcsServer::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return
    TAO::Narrow_Utils<tcsServer>::unchecked_narrow (
        _tao_objref,
        "IDL:alma/acstcsServer/tcsServer:1.0",
        acstcsServer__TAO_tcsServer_Proxy_Broker_Factory_function_pointer
      );
}

acstcsServer::tcsServer_ptr
acstcsServer::tcsServer::_duplicate (tcsServer_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  
  return obj;
}

void
acstcsServer::tcsServer::_tao_release (tcsServer_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
acstcsServer::tcsServer::_is_a (const char *value)
{
  if (
      !ACE_OS::strcmp (
          value,
          "IDL:alma/ACS/ACSComponent:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:alma/ACS/CharacteristicModel:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:alma/ACS/CharacteristicComponent:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:alma/acstcsServer/tcsServer:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* acstcsServer::tcsServer::_interface_repository_id (void) const
{
  return "IDL:alma/acstcsServer/tcsServer:1.0";
}

::CORBA::Boolean
acstcsServer::tcsServer::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// be/be_visitor_typecode/objref_typecode.cpp:76

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_acstcsServer_tcsServer (
    ::CORBA::tk_objref,
    "IDL:alma/acstcsServer/tcsServer:1.0",
    "tcsServer");
  
namespace acstcsServer
{
  ::CORBA::TypeCode_ptr const _tc_tcsServer =
    &_tao_tc_acstcsServer_tcsServer;
}



// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_cs.cpp:51
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<acstcsServer::tcsServer>::to_object (
      ::CORBA::Object_ptr &_tao_elem
    ) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace acstcsServer
{
  
  
  /// Copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      tcsServer_ptr _tao_elem)
  {
    tcsServer_ptr _tao_objptr =
      tcsServer::_duplicate (_tao_elem);
    _tao_any <<= &_tao_objptr;
  }
  
  /// Non-copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      tcsServer_ptr *_tao_elem)
  {
    TAO::Any_Impl_T<tcsServer>::insert (
        _tao_any,
        tcsServer::_tao_any_destructor,
        _tc_tcsServer,
        *_tao_elem)
  }
  
  ::CORBA::Boolean
  operator>>= (
      const ::CORBA::Any &_tao_any,
      tcsServer_ptr &_tao_elem)
  {
    return
      TAO::Any_Impl_T<tcsServer>::extract (
          _tao_any,
          tcsServer::_tao_any_destructor,
          _tc_tcsServer,
          _tao_elem)
  }
}

#else

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



/// Copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    acstcsServer::tcsServer_ptr _tao_elem)
{
  acstcsServer::tcsServer_ptr _tao_objptr =
    acstcsServer::tcsServer::_duplicate (_tao_elem);
  _tao_any <<= &_tao_objptr;
}

/// Non-copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    acstcsServer::tcsServer_ptr *_tao_elem)
{
  TAO::Any_Impl_T<acstcsServer::tcsServer>::insert (
      _tao_any,
      acstcsServer::tcsServer::_tao_any_destructor,
      acstcsServer::_tc_tcsServer,
      *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    acstcsServer::tcsServer_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<acstcsServer::tcsServer>::extract (
        _tao_any,
        acstcsServer::tcsServer::_tao_any_destructor,
        acstcsServer::_tc_tcsServer,
        _tao_elem);
}

TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_cs.cpp:63

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const acstcsServer::tcsServer_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    acstcsServer::tcsServer_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;
  
  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  typedef ::acstcsServer::tcsServer RHS_SCOPED_NAME;
  
  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (
        obj.in (),
        acstcsServer__TAO_tcsServer_Proxy_Broker_Factory_function_pointer
      );
    
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



