#ifndef _TCS_SERVER_IDL_
#define _TCS_SERVER_IDL_

#include <ACSErrTypeCommon.idl>

#pragma prefix "alma"

#include <baci.idl>


module acstcsServer {

	interface tcsServer : ACS::CharacteristicComponent
		{
		void displayMessage();
		void badMethod() raises (ACSErrTypeCommon::UnknownEx);
		
		readonly attribute ACS::RWdouble currentPositionAlpha;
		readonly attribute ACS::RWdouble currentPositionDelta;
		
		};
	
};

#endif

