#ifndef _DOME_SERVER_IDL_
#define _DOME_SERVER_IDL_

#include <ACSErrTypeCommon.idl>

#pragma prefix "alma"

#include <baci.idl>

module acsdomeServer 
{
    interface DomeServer : ACS::CharacteristicComponent
	{
	void displayMessage();
	void badMethod() raises (ACSErrTypeCommon::UnknownEx);
	//double getCurrentPosition();
	
	readonly attribute ACS::RWdouble domeCurrentPosition;
	readonly attribute ACS::RWlong slitCurrentState;
	};
};

#endif
