/* 
 * "@(#) $Id: irisGeo.idl,v 1.2 2010/01/02 09:14:47 mparra Exp $ 
 *
 * Revision 1.2 2010/01/02 09:14:47  mparra
 * - Adapted to IRIS telescope name.
 *
 */

#ifndef IRISGEO_IDL
#define IRISGEO_IDL

#include <baci.idl>

#pragma prefix "alma"

module irisGeo
{
  /* * * * * * * ACS distributed object for geographical position * * */

  interface Geo : ACS::CharacteristicComponent
  {
    /*
     * Antenna site mean longitude (radian).
     */
    readonly attribute ACS::RWdouble longitude;

    /*
     * Antenna site mean geodetic latitude (radian).
     */
    readonly attribute ACS::RWdouble latitude;

    /*
     * Antenna site height above sea level (meter).
     */
    readonly attribute ACS::RWdouble height;
  };
};
#endif
