#ifndef _DOMOTEST_IDL_
#define _DOMOTEST_IDL_

#include <acscomponent.idl>
#include <baci.idl>
#pragma prefix "alma"

module domotestModule{
	interface domotestInterface:ACS::ACSComponent {
		long getEstado();
	};
};
#endif
