#ifndef _TELESCOPE_SERVER_IDL
#define _TELESCOPE_SERVER_IDL

#include <ACSErrTypeCommon.idl>

#pragma prefix "alma"

#include <baci.idl>

module acstelescopeServer 
{
    interface TelescopeServer : ACS::CharacteristicComponent
	{
	void displayMessage();
	void badMethod() raises (ACSErrTypeCommon::UnknownEx);
	double startTelescope();
	double slewTelescope();
	double setAltitude();
	double getAzimuth();
		
	readonly attribute ACS::RWdouble currentPositionAlpha;
	readonly attribute ACS::RWdouble currentPositionDelta;
	};
};

#endif
