// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler v1.6.5 ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// be/be_codegen.cpp:381


#include "acsdomeServerC.h"
#include "tao/AnyTypeCode/Null_RefCount_Policy.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/AnyTypeCode/Alias_TypeCode_Static.h"
#include "tao/AnyTypeCode/Objref_TypeCode_Static.h"
#include "tao/AnyTypeCode/String_TypeCode_Static.h"
#include "tao/CDR.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "tao/CDR.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/AnyTypeCode/Any_Impl_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Object_Argument_T.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "acsdomeServerC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:73

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
  
  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:141

#if !defined (_ACS_RWDOUBLE__ARG_TRAITS_)
#define _ACS_RWDOUBLE__ARG_TRAITS_
  
  template<>
  class  Arg_Traits<ACS::RWdouble>
    : public
        Object_Arg_Traits_T<
            ACS::RWdouble_ptr,
            ACS::RWdouble_var,
            ACS::RWdouble_out,
            TAO::Objref_Traits<ACS::RWdouble>,
            TAO::Any_Insert_Policy_Stream <ACS::RWdouble_ptr>
          >
  {
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:141

#if !defined (_ACS_RWLONG__ARG_TRAITS_)
#define _ACS_RWLONG__ARG_TRAITS_
  
  template<>
  class  Arg_Traits<ACS::RWlong>
    : public
        Object_Arg_Traits_T<
            ACS::RWlong_ptr,
            ACS::RWlong_var,
            ACS::RWlong_out,
            TAO::Objref_Traits<ACS::RWlong>,
            TAO::Any_Insert_Policy_Stream <ACS::RWlong_ptr>
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:60

// Traits specializations for acsdomeServer::DomeServer.

acsdomeServer::DomeServer_ptr
TAO::Objref_Traits<acsdomeServer::DomeServer>::duplicate (
    acsdomeServer::DomeServer_ptr p)
{
  return acsdomeServer::DomeServer::_duplicate (p);
}

void
TAO::Objref_Traits<acsdomeServer::DomeServer>::release (
    acsdomeServer::DomeServer_ptr p)
{
  ::CORBA::release (p);
}

acsdomeServer::DomeServer_ptr
TAO::Objref_Traits<acsdomeServer::DomeServer>::nil (void)
{
  return acsdomeServer::DomeServer::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<acsdomeServer::DomeServer>::marshal (
    const acsdomeServer::DomeServer_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// Function pointer for collocation factory initialization.
TAO::Collocation_Proxy_Broker * 
(*acsdomeServer__TAO_DomeServer_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj
  ) = 0;

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void acsdomeServer::DomeServer::displayMessage (
    void)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_DomeServer_Proxy_Broker_ == 0)
    {
      acsdomeServer_DomeServer_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "displayMessage",
      14,
      this->the_TAO_DomeServer_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void acsdomeServer::DomeServer::badMethod (
    void)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_DomeServer_Proxy_Broker_ == 0)
    {
      acsdomeServer_DomeServer_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  static TAO::Exception_Data
  _tao_acsdomeServer_DomeServer_badMethod_exceptiondata [] = 
    {
      {
        "IDL:alma/ACSErrTypeCommon/UnknownEx:1.0",
        ACSErrTypeCommon::UnknownEx::_alloc
#if TAO_HAS_INTERCEPTORS == 1
        , ACSErrTypeCommon::_tc_UnknownEx
#endif /* TAO_HAS_INTERCEPTORS */
      }
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "badMethod",
      9,
      this->the_TAO_DomeServer_Proxy_Broker_
    );
  
  _tao_call.invoke (
      _tao_acsdomeServer_DomeServer_badMethod_exceptiondata,
      1
    );
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

::ACS::RWdouble_ptr acsdomeServer::DomeServer::domeCurrentPosition (
    void)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_DomeServer_Proxy_Broker_ == 0)
    {
      acsdomeServer_DomeServer_setup_collocation ();
    }
  
  TAO::Arg_Traits< ::ACS::RWdouble>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_domeCurrentPosition",
      24,
      this->the_TAO_DomeServer_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

::ACS::RWlong_ptr acsdomeServer::DomeServer::slitCurrentState (
    void)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_DomeServer_Proxy_Broker_ == 0)
    {
      acsdomeServer_DomeServer_setup_collocation ();
    }
  
  TAO::Arg_Traits< ::ACS::RWlong>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_slitCurrentState",
      21,
      this->the_TAO_DomeServer_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
  
  return _tao_retval.retn ();
}

acsdomeServer::DomeServer::DomeServer (void)
 : the_TAO_DomeServer_Proxy_Broker_ (0)
{
  this->acsdomeServer_DomeServer_setup_collocation ();
}

void
acsdomeServer::DomeServer::acsdomeServer_DomeServer_setup_collocation ()
{
  if (::acsdomeServer__TAO_DomeServer_Proxy_Broker_Factory_function_pointer)
    {
      this->the_TAO_DomeServer_Proxy_Broker_ =
        ::acsdomeServer__TAO_DomeServer_Proxy_Broker_Factory_function_pointer (this);
    }
  
  this->ACS_CharacteristicComponent_setup_collocation ();
}

acsdomeServer::DomeServer::~DomeServer (void)
{}

void 
acsdomeServer::DomeServer::_tao_any_destructor (void *_tao_void_pointer)
{
  DomeServer *_tao_tmp_pointer =
    static_cast<DomeServer *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

acsdomeServer::DomeServer_ptr
acsdomeServer::DomeServer::_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return
    TAO::Narrow_Utils<DomeServer>::narrow (
        _tao_objref,
        "IDL:alma/acsdomeServer/DomeServer:1.0",
        acsdomeServer__TAO_DomeServer_Proxy_Broker_Factory_function_pointer
      );
}

acsdomeServer::DomeServer_ptr
acsdomeServer::DomeServer::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return
    TAO::Narrow_Utils<DomeServer>::unchecked_narrow (
        _tao_objref,
        "IDL:alma/acsdomeServer/DomeServer:1.0",
        acsdomeServer__TAO_DomeServer_Proxy_Broker_Factory_function_pointer
      );
}

acsdomeServer::DomeServer_ptr
acsdomeServer::DomeServer::_duplicate (DomeServer_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  
  return obj;
}

void
acsdomeServer::DomeServer::_tao_release (DomeServer_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
acsdomeServer::DomeServer::_is_a (const char *value)
{
  if (
      !ACE_OS::strcmp (
          value,
          "IDL:alma/ACS/ACSComponent:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:alma/ACS/CharacteristicModel:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:alma/ACS/CharacteristicComponent:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:alma/acsdomeServer/DomeServer:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* acsdomeServer::DomeServer::_interface_repository_id (void) const
{
  return "IDL:alma/acsdomeServer/DomeServer:1.0";
}

::CORBA::Boolean
acsdomeServer::DomeServer::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// be/be_visitor_typecode/objref_typecode.cpp:76

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_acsdomeServer_DomeServer (
    ::CORBA::tk_objref,
    "IDL:alma/acsdomeServer/DomeServer:1.0",
    "DomeServer");
  
namespace acsdomeServer
{
  ::CORBA::TypeCode_ptr const _tc_DomeServer =
    &_tao_tc_acsdomeServer_DomeServer;
}



// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_cs.cpp:51
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<acsdomeServer::DomeServer>::to_object (
      ::CORBA::Object_ptr &_tao_elem
    ) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace acsdomeServer
{
  
  
  /// Copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      DomeServer_ptr _tao_elem)
  {
    DomeServer_ptr _tao_objptr =
      DomeServer::_duplicate (_tao_elem);
    _tao_any <<= &_tao_objptr;
  }
  
  /// Non-copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      DomeServer_ptr *_tao_elem)
  {
    TAO::Any_Impl_T<DomeServer>::insert (
        _tao_any,
        DomeServer::_tao_any_destructor,
        _tc_DomeServer,
        *_tao_elem)
  }
  
  ::CORBA::Boolean
  operator>>= (
      const ::CORBA::Any &_tao_any,
      DomeServer_ptr &_tao_elem)
  {
    return
      TAO::Any_Impl_T<DomeServer>::extract (
          _tao_any,
          DomeServer::_tao_any_destructor,
          _tc_DomeServer,
          _tao_elem)
  }
}

#else

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



/// Copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    acsdomeServer::DomeServer_ptr _tao_elem)
{
  acsdomeServer::DomeServer_ptr _tao_objptr =
    acsdomeServer::DomeServer::_duplicate (_tao_elem);
  _tao_any <<= &_tao_objptr;
}

/// Non-copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    acsdomeServer::DomeServer_ptr *_tao_elem)
{
  TAO::Any_Impl_T<acsdomeServer::DomeServer>::insert (
      _tao_any,
      acsdomeServer::DomeServer::_tao_any_destructor,
      acsdomeServer::_tc_DomeServer,
      *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    acsdomeServer::DomeServer_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<acsdomeServer::DomeServer>::extract (
        _tao_any,
        acsdomeServer::DomeServer::_tao_any_destructor,
        acsdomeServer::_tc_DomeServer,
        _tao_elem);
}

TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_cs.cpp:63

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const acsdomeServer::DomeServer_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    acsdomeServer::DomeServer_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;
  
  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  typedef ::acsdomeServer::DomeServer RHS_SCOPED_NAME;
  
  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (
        obj.in (),
        acsdomeServer__TAO_DomeServer_Proxy_Broker_Factory_function_pointer
      );
    
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



