#ifndef _DOME_SERVER_IDL_
#define _DOME_SERVER_IDL_

#include <acscomponent.idl>
#include <ACSErrTypeCommon.idl>

#pragma prefix "alma"

module acsdomeServer 
{
    interface DomeServer : ACS::ACSComponent
	{
	void displayMessage();
	
	double getCurrentPosition();
	boolean rotateDome(in double radians);
	boolean domeSlitIsOpen();
    boolean openDomeSlit();
    boolean closeDomeSlit();
    
	void badMethod() raises (ACSErrTypeCommon::UnknownEx);
	};
};

#endif
