// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler v1.6.5 ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// be/be_codegen.cpp:135

#ifndef _TAO_IDL____OBJECT_ACSDOMESERVERC_H_
#define _TAO_IDL____OBJECT_ACSDOMESERVERC_H_


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Objref_VarOut_T.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "acscomponentC.h"
#include "ACSErrTypeCommonC.h"

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from 
// be/be_visitor_root/root_ch.cpp:62
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  class Collocation_Proxy_Broker;
  template<typename T> class Narrow_Utils;
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:49

namespace acsdomeServer
{
  
  // TAO_IDL - Generated from
  // be/be_interface.cpp:644

#if !defined (_ACSDOMESERVER_DOMESERVER__VAR_OUT_CH_)
#define _ACSDOMESERVER_DOMESERVER__VAR_OUT_CH_
  
  class DomeServer;
  typedef DomeServer *DomeServer_ptr;
  
  typedef
    TAO_Objref_Var_T<
        DomeServer
      >
    DomeServer_var;
  
  typedef
    TAO_Objref_Out_T<
        DomeServer
      >
    DomeServer_out;

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:54

#if !defined (_ACSDOMESERVER_DOMESERVER_CH_)
#define _ACSDOMESERVER_DOMESERVER_CH_
  
  class  DomeServer
    : public virtual ::ACS::ACSComponent
  {
  public:
    friend class TAO::Narrow_Utils<DomeServer>;
    typedef DomeServer_ptr _ptr_type;
    typedef DomeServer_var _var_type;
    typedef DomeServer_out _out_type;
    
    // The static operations.
    static DomeServer_ptr _duplicate (DomeServer_ptr obj);
    
    static void _tao_release (DomeServer_ptr obj);
    
    static DomeServer_ptr _narrow (::CORBA::Object_ptr obj);
    static DomeServer_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static DomeServer_ptr _nil (void)
    {
      return static_cast<DomeServer_ptr> (0);
    }
    
    static void _tao_any_destructor (void *);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual void displayMessage (
        void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual void badMethod (
        void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:216
    
    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  private:
    TAO::Collocation_Proxy_Broker *the_TAO_DomeServer_Proxy_Broker_;
  
  protected:
    // Concrete interface only.
    DomeServer (void);
    
    // These methods travese the inheritance tree and set the
    // parents piece of the given class in the right mode.
    virtual void acsdomeServer_DomeServer_setup_collocation (void);
    
    // Concrete non-local interface only.
    DomeServer (
        IOP::IOR *ior,
        TAO_ORB_Core *orb_core = 0);
    
    // Non-local interface only.
    DomeServer (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = 0,
        TAO_ORB_Core *orb_core = 0);
    
    virtual ~DomeServer (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    DomeServer (const DomeServer &);
    
    void operator= (const DomeServer &);
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_DomeServer;

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:78

} // module acsdomeServer

// Proxy Broker Factory function pointer declarations.

// TAO_IDL - Generated from
// be/be_visitor_root/root.cpp:139

extern 
TAO::Collocation_Proxy_Broker *
(*acsdomeServer__TAO_DomeServer_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj
  );

// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:64

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_ACSDOMESERVER_DOMESERVER__TRAITS_)
#define _ACSDOMESERVER_DOMESERVER__TRAITS_
  
  template<>
  struct  Objref_Traits< ::acsdomeServer::DomeServer>
  {
    static ::acsdomeServer::DomeServer_ptr duplicate (
        ::acsdomeServer::DomeServer_ptr p
      );
    static void release (
        ::acsdomeServer::DomeServer_ptr p
      );
    static ::acsdomeServer::DomeServer_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::acsdomeServer::DomeServer_ptr p,
        TAO_OutputCDR & cdr
      );
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_ch.cpp:54



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace acsdomeServer
{
   void operator<<= ( ::CORBA::Any &, DomeServer_ptr); // copying
   void operator<<= ( ::CORBA::Any &, DomeServer_ptr *); // non-copying
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DomeServer_ptr &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, acsdomeServer::DomeServer_ptr); // copying
 void operator<<= (::CORBA::Any &, acsdomeServer::DomeServer_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, acsdomeServer::DomeServer_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_ch.cpp:55

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const acsdomeServer::DomeServer_ptr );
 ::CORBA::Boolean operator>> (TAO_InputCDR &, acsdomeServer::DomeServer_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1226
#if defined (__ACE_INLINE__)
#include "acsdomeServerC.inl"
#endif /* defined INLINE */

#endif /* ifndef */


