// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler v1.6.5 ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// be/be_codegen.cpp:381


#include "domeServerC.h"
#include "tao/AnyTypeCode/Null_RefCount_Policy.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/AnyTypeCode/Alias_TypeCode_Static.h"
#include "tao/AnyTypeCode/Objref_TypeCode_Static.h"
#include "tao/AnyTypeCode/String_TypeCode_Static.h"
#include "tao/CDR.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "tao/CDR.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/AnyTypeCode/Any_Impl_T.h"
#include "tao/Special_Basic_Arguments.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "domeServerC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:73

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:60

// Traits specializations for domeServerModule::domeServertInterface.

domeServerModule::domeServertInterface_ptr
TAO::Objref_Traits<domeServerModule::domeServertInterface>::duplicate (
    domeServerModule::domeServertInterface_ptr p)
{
  return domeServerModule::domeServertInterface::_duplicate (p);
}

void
TAO::Objref_Traits<domeServerModule::domeServertInterface>::release (
    domeServerModule::domeServertInterface_ptr p)
{
  ::CORBA::release (p);
}

domeServerModule::domeServertInterface_ptr
TAO::Objref_Traits<domeServerModule::domeServertInterface>::nil (void)
{
  return domeServerModule::domeServertInterface::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<domeServerModule::domeServertInterface>::marshal (
    const domeServerModule::domeServertInterface_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// Function pointer for collocation factory initialization.
TAO::Collocation_Proxy_Broker * 
(*domeServerModule__TAO_domeServertInterface_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj
  ) = 0;

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

::CORBA::Boolean domeServerModule::domeServertInterface::getStatus (
    void)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_domeServertInterface_Proxy_Broker_ == 0)
    {
      domeServerModule_domeServertInterface_setup_collocation ();
    }
  
  TAO::Arg_Traits< ::ACE_InputCDR::to_boolean>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "getStatus",
      9,
      this->the_TAO_domeServertInterface_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
  
  return _tao_retval.retn ();
}

domeServerModule::domeServertInterface::domeServertInterface (void)
 : the_TAO_domeServertInterface_Proxy_Broker_ (0)
{
  this->domeServerModule_domeServertInterface_setup_collocation ();
}

void
domeServerModule::domeServertInterface::domeServerModule_domeServertInterface_setup_collocation ()
{
  if (::domeServerModule__TAO_domeServertInterface_Proxy_Broker_Factory_function_pointer)
    {
      this->the_TAO_domeServertInterface_Proxy_Broker_ =
        ::domeServerModule__TAO_domeServertInterface_Proxy_Broker_Factory_function_pointer (this);
    }
  
  this->ACS_ACSComponent_setup_collocation ();
}

domeServerModule::domeServertInterface::~domeServertInterface (void)
{}

void 
domeServerModule::domeServertInterface::_tao_any_destructor (void *_tao_void_pointer)
{
  domeServertInterface *_tao_tmp_pointer =
    static_cast<domeServertInterface *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

domeServerModule::domeServertInterface_ptr
domeServerModule::domeServertInterface::_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return
    TAO::Narrow_Utils<domeServertInterface>::narrow (
        _tao_objref,
        "IDL:alma/domeServerModule/domeServertInterface:1.0",
        domeServerModule__TAO_domeServertInterface_Proxy_Broker_Factory_function_pointer
      );
}

domeServerModule::domeServertInterface_ptr
domeServerModule::domeServertInterface::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return
    TAO::Narrow_Utils<domeServertInterface>::unchecked_narrow (
        _tao_objref,
        "IDL:alma/domeServerModule/domeServertInterface:1.0",
        domeServerModule__TAO_domeServertInterface_Proxy_Broker_Factory_function_pointer
      );
}

domeServerModule::domeServertInterface_ptr
domeServerModule::domeServertInterface::_duplicate (domeServertInterface_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  
  return obj;
}

void
domeServerModule::domeServertInterface::_tao_release (domeServertInterface_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
domeServerModule::domeServertInterface::_is_a (const char *value)
{
  if (
      !ACE_OS::strcmp (
          value,
          "IDL:alma/ACS/ACSComponent:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:alma/domeServerModule/domeServertInterface:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* domeServerModule::domeServertInterface::_interface_repository_id (void) const
{
  return "IDL:alma/domeServerModule/domeServertInterface:1.0";
}

::CORBA::Boolean
domeServerModule::domeServertInterface::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// be/be_visitor_typecode/objref_typecode.cpp:76

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_domeServerModule_domeServertInterface (
    ::CORBA::tk_objref,
    "IDL:alma/domeServerModule/domeServertInterface:1.0",
    "domeServertInterface");
  
namespace domeServerModule
{
  ::CORBA::TypeCode_ptr const _tc_domeServertInterface =
    &_tao_tc_domeServerModule_domeServertInterface;
}



// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_cs.cpp:51
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<domeServerModule::domeServertInterface>::to_object (
      ::CORBA::Object_ptr &_tao_elem
    ) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace domeServerModule
{
  
  
  /// Copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      domeServertInterface_ptr _tao_elem)
  {
    domeServertInterface_ptr _tao_objptr =
      domeServertInterface::_duplicate (_tao_elem);
    _tao_any <<= &_tao_objptr;
  }
  
  /// Non-copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      domeServertInterface_ptr *_tao_elem)
  {
    TAO::Any_Impl_T<domeServertInterface>::insert (
        _tao_any,
        domeServertInterface::_tao_any_destructor,
        _tc_domeServertInterface,
        *_tao_elem)
  }
  
  ::CORBA::Boolean
  operator>>= (
      const ::CORBA::Any &_tao_any,
      domeServertInterface_ptr &_tao_elem)
  {
    return
      TAO::Any_Impl_T<domeServertInterface>::extract (
          _tao_any,
          domeServertInterface::_tao_any_destructor,
          _tc_domeServertInterface,
          _tao_elem)
  }
}

#else

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



/// Copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    domeServerModule::domeServertInterface_ptr _tao_elem)
{
  domeServerModule::domeServertInterface_ptr _tao_objptr =
    domeServerModule::domeServertInterface::_duplicate (_tao_elem);
  _tao_any <<= &_tao_objptr;
}

/// Non-copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    domeServerModule::domeServertInterface_ptr *_tao_elem)
{
  TAO::Any_Impl_T<domeServerModule::domeServertInterface>::insert (
      _tao_any,
      domeServerModule::domeServertInterface::_tao_any_destructor,
      domeServerModule::_tc_domeServertInterface,
      *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    domeServerModule::domeServertInterface_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<domeServerModule::domeServertInterface>::extract (
        _tao_any,
        domeServerModule::domeServertInterface::_tao_any_destructor,
        domeServerModule::_tc_domeServertInterface,
        _tao_elem);
}

TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_cs.cpp:63

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const domeServerModule::domeServertInterface_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    domeServerModule::domeServertInterface_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;
  
  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  typedef ::domeServerModule::domeServertInterface RHS_SCOPED_NAME;
  
  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (
        obj.in (),
        domeServerModule__TAO_domeServertInterface_Proxy_Broker_Factory_function_pointer
      );
    
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



